name: Portfolio Actions Workflow

on:
  push:
    branches: [dev]
  pull_request:
    branches: [dev]

jobs:
  Test-App:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@v2
      - name: run tests with Node.js v${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install NodeJS dependencies
        run: yarn install --frozen-lockfile
      - name: Run tests
        run: yarn test
